# Generated by Django 3.1.7 on 2021-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210331_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ManyToManyField(related_name='city', to='upload.City'),
        ),
    ]
